export default [
  {
    "productId": 0,
    "productName": "리스토베이",
    "productPreview": "쉽고 똑똑하게, 온라인 설문 제작 플랫폼",
    "benefitPreview": "연결제 시 5% 할인",
    "tag1": "🔮 마케팅툴",
    "tag2": "📊 분석툴",
    "tag3": "💻 노코드",
    "productDetail": "리스토베이는 누구든지 쉽고 간편하게 설문을 제작하고, 다양한 방식으로 배포할 수 있으며 실시간으로 수집된 응답을 분석하여 리포트를 제공하는 온라인 설문 플랫폼입니다.",
    "benefitDetail": "연결제 시 5% 할인",
    "isMakerlog": 0,
    "makerlogTitle": "",
    "makerlogPreviewtext": "",
    "makerlogLink": "",
    "profileImg": "https://assets.disquiet.io/images/profile/33dca4b1bb83f3aced14526e0810fc78946434516169e942c36400c5176fc94d",
    "profileName": "listovey",
    "profileRole": "CEO @Listovey",
    "profileLink": "https://disquiet.io/@listovey_platfrom?utm_source=makerkit",
    "productLink": "https://disquiet.io/product/%EB%A6%AC%EC%8A%A4%ED%86%A0%EB%B2%A0%EC%9D%B4?utm_source=makerkit",
    "tallyLink": "https://tally.so/r/3yPG5B",
    "popularity": ""
  },
  {
    "productId": 1,
    "productName": "도다",
    "productPreview": "응답하고 싶은 인터랙티브 폼",
    "benefitPreview": "무료 플랜 업그레이드 1개월 제공",
    "tag1": "🔮 마케팅툴",
    "tag2": "💻 노코드",
    "tag3": "🚲 생산성",
    "productDetail": "Into the Mind of Your Customer. 사람 중심으로, 쉽고 빠르게, 좋은 질문을 할 수 있는 서베이 폼 서비스입니다. 응답자 친화적인 UX와 몰입감을 자랑합니다.",
    "benefitDetail": "무료 플랜 업그레이드 1개월 제공",
    "isMakerlog": 1,
    "makerlogTitle": "드디어 한 방이 제대로 들어갔다.",
    "makerlogPreviewtext": "프리미엄 플랜의 2nd month retention이 14%나 올라갔다. HYBE가 작년 4월에 처음 우리 데모를 쓸 때가 생각난다. 1달 만에 만든 목업 데모를 돈주고 쓰겠다는 HYBE는 엄청난 기능 피드백을 줬고...",
    "makerlogLink": "https://disquiet.io/@doda_tool/makerlog/1047?utm_source=makerkit",
    "profileImg": "https://assets.disquiet.io/images/profile/1ae37579fe0ba6f80fff890ef3fb610ec533513aa8b43368ce468b1d0d8c6f46",
    "profileName": "곽도영",
    "profileRole": "CEO @(주)도다마인드",
    "profileLink": "https://disquiet.io/@doda_tool?utm_source=makerkit",
    "productLink": "https://disquiet.io/product/%EB%8F%84%EB%8B%A4-%ED%88%B4?utm_source=makerkit",
    "tallyLink": "https://tally.so/r/3yPG5B",
    "popularity": 4
  },
  {
    "productId": 2,
    "productName": "페넷 체커",
    "productPreview": "모바일 앱 취약점 자동 진단 엔진",
    "benefitPreview": "취약점 진단 결과에 대한 <br> Private Q&A 세션 무료 제공",
    "tag1": "🧑‍💻 개발툴",
    "tag2": "📊 분석툴",
    "tag3": "🚲 생산성",
    "productDetail": "페넷은 어렵고 비싸다고 여겨지던 보안을 쉽고 간편하게 만듭니다! 화이트 해커가 직접 큐레이션한 진단 항목으로 앱의 보안 취약점을 쉽게 찾고 조치하세요!",
    "benefitDetail": "-페넷 체커를 통해 모바일 앱 취약점 진단 결과에 대한 Private Q&A 세션 무료 제공<br>-정식 버전 출시(2023년 1월 예정) 이후, 이용 요금 할인 혜택 제공",
    "isMakerlog": 1,
    "makerlogTitle": "정보보안 비용을 15배 아끼는 방법",
    "makerlogPreviewtext": "오늘날 소프트웨어 개발 라이프 사이클(SDLC)은 크게 [요구사항수집 - 기획 - 개발(코딩) - 테스트 - 배포 - 유지보수]로 이루어져 있습니다. 소수의 인원으로 구성된 초기 스타트업은 테스트를 위한 QA인력을 별도로 구성하기 어려워...",
    "makerlogLink": "https://disquiet.io/@wonderz/makerlog/1249?utm_source=makerkit",
    "profileImg": "https://assets.disquiet.io/images/profile/220cd0163cb99a0e27bf35a181e8197087384d17789a2209abf45078b86b4ebc",
    "profileName": "김기명",
    "profileRole": "CEO @주식회사 월간해킹",
    "profileLink": "https://disquiet.io/@wonderz?utm_source=makerkit",
    "productLink": "https://disquiet.io/product/%ED%8E%98%EB%84%B7-%EC%B2%B4%EC%BB%A4?utm_source=makerkit",
    "tallyLink": "https://tally.so/r/3yPG5B",
    "popularity": ""
  },
  {
    "productId": 3,
    "productName": "애드샐러드",
    "productPreview": "트래킹 툴을 사용할 수 있도록 돕는 <br> 리타게팅 링크 서비스",
    "benefitPreview": "프리미엄 플랜 1개월 무료 혜택",
    "tag1": "🔮 마케팅툴",
    "tag2": "📊 분석툴",
    "tag3": "🚲 생산성",
    "productDetail": "리타게팅 링크를 생성하고 관리할 수 있는 리타게팅 링크 매니지먼트 서비스 '애드샐러드'입니다.<br><br>스크립트 설치가 안되는 플랫폼에서도 픽셀 등의 트래킹 툴을 우회해서 사용할 수 있도록 돕는 마케팅 도구입니다. 링크 클릭 후 랜딩페이지로 유입되는 과정에서 스크립트가 동작하게 해 방문자 데이터를 수집, 분석하실 수 있습니다.",
    "benefitDetail": "프리미엄 플랜 1개월 무료 혜택",
    "isMakerlog": 1,
    "makerlogTitle": "노코드로 '실제 서비스 되는' 프로덕트를 만들 수 있을까?",
    "makerlogPreviewtext": "애드샐러드의 최초 프로덕트는 개발 외주로 제작된 것이었습니다. 기획을 들고 개발 전문사와 미팅 후 외주 비용을 치르고...",
    "makerlogLink": "https://disquiet.io/@hweedongs/makerlog/566?utm_source=makerkit",
    "profileImg": "https://assets.disquiet.io/images/profile/2e538a3da5a04979c32e062e6e0e7a45094431f62d897d37fdfe5a08c9dc9a14",
    "profileName": "하희철",
    "profileRole": "메이커 @놀라운형제들",
    "profileLink": "https://disquiet.io/@hweedongs?utm_source=makerkit",
    "productLink": "https://disquiet.io/product/%EC%95%A0%EB%93%9C%EC%83%90%EB%9F%AC%EB%93%9C?utm_source=makerkit",
    "tallyLink": "https://tally.so/r/3yPG5B",
    "popularity": ""
  },
  {
    "productId": 4,
    "productName": "Oopy. 우피",
    "productPreview": "노션을 이용한 노코드 웹페이지 빌더",
    "benefitPreview": "무료 체험 기간(1주일)동안 <br> 프로 플랜 사용",
    "tag1": "🔮 마케팅툴",
    "tag2": "💻 노코드",
    "tag3": "🚲 생산성",
    "productDetail": "노션을 이용해 웹페이지를 만드는데 필요한 2%를 제공하는 서비스입니다. 더 많은 분들이 쉽게 웹페이지를 만들고, 수정하고, 배포하고, 성장했으면 좋겠어요! 그러기 위해 필요한 부분을 언제나 듣고 싶습니다 :)",
    "benefitDetail": "무료 체험 기간(1주일)동안 프로 플랜 사용 가능하도록 할 수 있습니다. (현재 베이직 플랜만 무료 체험 가능)",
    "isMakerlog": 0,
    "makerlogTitle": "",
    "makerlogPreviewtext": "",
    "makerlogLink": "",
    "profileImg": "https://assets.disquiet.io/images/profile/4d14615ebca2d0a50fe0c00142c0cc5eb546507de1c685eda3be5ce112d8a5cc",
    "profileName": "최종욱",
    "profileRole": "Founder @Oopy",
    "profileLink": "https://disquiet.io/@johnwook?utm_source=makerkit",
    "productLink": "https://disquiet.io/product/oopy.-%EC%9A%B0%ED%94%BC?utm_source=makerkit",
    "tallyLink": "https://tally.so/r/3yPG5B",
    "popularity": 1
  },
  {
    "productId": 5,
    "productName": "센드타임",
    "productPreview": "B2B 비즈니스 미팅 스케줄링에는 sendtime!",
    "benefitPreview": "개인 및 그룹 스케줄링 무제한 사용 <br>+ 무료 사용 기간을 기본 3개월",
    "tag1": "💸 세일즈",
    "tag2": "🚲 생산성",
    "tag3": "📷 라이프스타일",
    "productDetail": "🗣️ 시간 언제 괜찮으세요?<br>👤 센드타임으로 조율할까요?<br><br>📅 “조율은 빨리, 기회는 많이”<br>스케줄링은 업무가 아니에요. 조율하는 시간을 다른 곳에 의미있게 사용하세요",
    "benefitDetail": "센드타임 유료화시, 디스콰이엇을 통해 들어오는 분들의 경우 \"개인 및 그룹 스케줄링\" 무제한 사용 + 무료 사용 기간을 기본 1개월을 \"3개월\"로 늘려드리고자 합니다 ✨",
    "isMakerlog": 1,
    "makerlogTitle": "Heading to San Francisco!✈️ 센드타임, 글로벌도 도전해보자!",
    "makerlogPreviewtext": "오늘부터 10일간 500 Global Founders Retreat 에 참여하게됩니다! 정말 두근거리고, 스플랩/센드타임에게 글로벌 진출의 시작이 될 것만 같은 기분이 들어서 너무...",
    "makerlogLink": "https://disquiet.io/@splab_ceo/makerlog/1219?utm_source=makerkit",
    "profileImg": "https://assets.disquiet.io/images/profile/cc4dfc318e30f1e0ab89b9455a03372548e1b6444876777e88d118287155204f",
    "profileName": "선민승",
    "profileRole": "CEO @Splab Inc",
    "profileLink": "https://disquiet.io/@splab_ceo?utm_source=makerkit",
    "productLink": "https://disquiet.io/product/%EC%84%BC%EB%93%9C%ED%83%80%EC%9E%84?utm_source=makerkit",
    "tallyLink": "https://tally.so/r/3yPG5B",
    "popularity": 3
  },
  {
    "productId": 6,
    "productName": "타입드",
    "productPreview": "지식관리 기반 문서 툴",
    "benefitPreview": "3개월 간 58% 월 구독료 할인",
    "tag1": "🚲 생산성",
    "tag2": "",
    "tag3": "",
    "productDetail": "왜 우리의 워드프로세스는 어떤 문서를 작성할 때, 내가 수집하고 조회하는 자료에는 무관심했을까요?<br>작성하는 문서의 컨텍스트에 맞게 리소스를 쉽게 찾고, 심지어 추천 받아 활용 할 수 있다면 어떨까요?<br><br>타입드(Typed)의 여정은 그러한 근본적인 질문에서 출발하였습니다.<br>Doc, Ppt, Excel 등 기존에 사용하시는 문서 툴을 필요에 맞게 그대로 쓰시고,<br>모든 리소스 관리와 추천은 타입드가 책임 집니다!",
    "benefitDetail": "3개월 간 58% 월 구독료 할인",
    "isMakerlog": 1,
    "makerlogTitle": "[성장하는 사람들과 하루하루 인생을 나아간다는 것]",
    "makerlogPreviewtext": "스타트업을 하다보면 정말 ‘짜릿'한 순간들도 종종 찾아오곤 하지만, 그러한 순간들은 잠깐 ‘반짝'하고 지나가 버리기 마련인 것 같아요. 계속해서 더 큰 도전이 앞에 기다리고 있고, 예상치 못한 변수가 또 발생하기 마련이고…",
    "makerlogLink": "https://disquiet.io/@woojin_kim/makerlog/53?utm_source=makerkit",
    "profileImg": "https://assets.disquiet.io/images/profile/0d6581fc8377033ce511fda155076050ca235bd24beb145901b1484ecbf0fdf3",
    "profileName": "Woojin Kim",
    "profileRole": "CEO @비즈니스캔버스",
    "profileLink": "https://disquiet.io/@woojin_kim?utm_source=makerkit",
    "productLink": "https://disquiet.io/product/타입드/?utm_source=makerkit",
    "tallyLink": "https://tally.so/r/3yPG5B",
    "popularity": 1
  },
  {
    "productId": 7,
    "productName": "뤼튼 카피라이팅",
    "productPreview": "시간을 아껴주는<br> 나만의 AI 카피라이터",
    "benefitPreview": "얼리 액세스 혜택 제공",
    "tag1": "🔮 마케팅툴",
    "tag2": "🤖 인공지능",
    "tag3": "🚲 생산성",
    "productDetail": "👉🏻 뤼튼 카피라이팅(wrtn Copywriting)은 초거대 모델을 활용하여 문장 생성을 도와주는 AI 카피라이터에요! 😀<br>👉🏻 글쓰기가 발생하는 다양한 상황에서 Ideation을 돕고 좋은 결과물의 생성을 통해 여러분의 시간을 아껴드립니다.",
    "benefitDetail": "뤼튼 카피라이팅의 얼리 액세스 혜택을 제공해드립니다! 🥰",
    "isMakerlog": 0,
    "makerlogTitle": "",
    "makerlogPreviewtext": "",
    "makerlogLink": "",
    "profileImg": "https://assets.disquiet.io/images/profile/30a5d24d215e0c28612efed47e8c2fcc838f02aa7fd4a8ed9f44db47b35ad40f",
    "profileName": "유영준",
    "profileRole": "Head of Business@뤼튼테크놀로지스",
    "profileLink": "https://disquiet.io/@derek?utm_source=makerkit",
    "productLink": "https://disquiet.io/product/뤼튼-카피라이팅/?utm_source=makerkit",
    "tallyLink": "https://tally.so/r/3yPG5B",
    "popularity": 1
  },
  {
    "productId": 8,
    "productName": "싱크트리",
    "productPreview": "백엔드 노코드 개발 솔루션",
    "benefitPreview": "할인 및 무료 사용",
    "tag1": "🧑‍💻 개발툴",
    "tag2": "💻 노코드",
    "tag3": "🚲 생산성",
    "productDetail": "싱크트리는 개발 외 업무로 힘들어하는 개발자와 기업을 위해 탄생했습니다. 지금도 수많은 백엔드 개발자들이 프로젝트 때마다 새로운 환경 설정과 반복적인 배포 과정 때문에 개발을 시작하기도 전에 힘들어 하고 있습니다.<br><br>게다가, 자금력이 부족한 초기 스타트업의 경우, 인프라, 서버 등 환경 설정 비용 부담으로 인해 프로젝트가 무산되는 경우도 있죠.<br><br>쉬운 사용 방법, 즉각적인 생산성, 무료 사용으로도 누구나 개발 가능한 접근성까지 이제 싱크트리와 함께 개발 본연의 업무와 비즈니스 확장에 집중하세요!",
    "benefitDetail": "할인, 무료 사용",
    "isMakerlog": 1,
    "makerlogTitle": "싱크트리 기술 블로그 오픈!",
    "makerlogPreviewtext": "싱크트리 기술 블로그에서는 '엔터플 개발 문화', '싱크트리를 활용한 개발 사례', '싱크트리 관련 기술 이야기' 등의 소식을 만나보실 수 있습니다.",
    "makerlogLink": "https://disquiet.io/@grace_ntuple/makerlog/1734?utm_source=makerkit",
    "profileImg": "https://assets.disquiet.io/images/profile/2432e061e55aa05424415bfe17bf4b64188a779dd2a56201ba4967231c86f78c",
    "profileName": "Grace Nam",
    "profileRole": "마케팅 @엔터플",
    "profileLink": "https://disquiet.io/@grace_ntuple?utm_source=makerkit",
    "productLink": "https://disquiet.io/product/%EC%8B%B1%ED%81%AC%ED%8A%B8%EB%A6%AC?utm_source=makerkit",
    "tallyLink": "https://tally.so/r/3yPG5B",
    "popularity": ""
  },
  {
    "productId": 9,
    "productName": "데이터너겟",
    "productPreview": "봐야 할 리포트만 전달하고,<br> 지금 필요한 솔루션을 추천해요.",
    "benefitPreview": "트랜잭션 툴 1회 무상 유지보수 <br> 또는 무료 기본설치",
    "tag1": "🔮 마케팅툴",
    "tag2": "📊 분석툴",
    "tag3": "🤖 인공지능",
    "productDetail": "GA4, Facebook Ads 등 수많은 리포트 중 봐야할 데이터만 큐레이팅하여 시각화 된 리포트로 볼 수 있는 서비스입니다.<br><br>그로스해킹의 가설/ 실험/ 검증에 충실하기 위한 서비스들을 고민하고 개선해나가고 있습니다.",
    "benefitDetail": "현재 사용하고 있는 트랜잭션 툴(GA4, appsflyer, firebase 등)의 1회 무상 유지보수, 혹은 무료 기본설치 (이벤트 5개 추적)",
    "isMakerlog": 1,
    "makerlogTitle": "그로스해킹 솔루션, 그로스해킹 하기.",
    "makerlogPreviewtext": "제가 보려는게 그렇게 대단한 건 아니잖아요...저희는 LABBIT이라는 브랜드로 그로스해킹 서비스를 제공했습니다. 고객사의 KPI를 함께 고민하며 천여개의 고객사를 만나보니, 주된 니즈가...",
    "makerlogLink": "https://disquiet.io/@jaewoo/makerlog/1736?utm_source=makerkit",
    "profileImg": "https://assets.disquiet.io/images/profile/eb610fbca90b7b23dd96c063b1989a2fe74cb43e8e608071f3f71e7bbb53ff47",
    "profileName": "최재우",
    "profileRole": "대표이사 @(주) 위어드섹터",
    "profileLink": "https://disquiet.io/@jaewoo?utm_source=makerkit",
    "productLink": "https://disquiet.io/product/%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%84%88%EA%B2%9F?utm_source=makerkit",
    "tallyLink": "https://tally.so/r/3yPG5B",
    "popularity": ""
  },
  {
    "productId": 10,
    "productName": "스티비",
    "productPreview": "이메일 뉴스레터 서비스",
    "benefitPreview": "30% 할인 쿠폰을 제공",
    "tag1": "🔮 마케팅툴",
    "tag2": "💻 노코드",
    "tag3": "🎙 미디어",
    "productDetail": "스티비는 뉴스레터의 제작과 발송, 마케팅을 돕는 이메일 뉴스레터 서비스입니다. 누구나 쉽고 깔끔하게 뉴스레터를 발송하고, 구독자와의 특별한 관계를 경험할 수 있도록 스티비가 다양한 기능과 정보를 제공하고 있습니다.<br>앞으로 어떤 방향으로 나아가야 할지 여러 고민을 하고 있고, 디스콰이엇에 계신 분들과도 이야기를 나눠보고 싶습니다. 🙂",
    "benefitDetail": "디스콰이엇 사용자 중, 스티비를 사용해보고 싶으시다면 30% 할인 쿠폰을 제공해드릴 수 있습니다. 제공 방법은 스티비 제휴 할인 신청 폼에 미리 지정한 할인 코드를 입력하여 확인하는 방식으로 진행됩니다.",
    "isMakerlog": 0,
    "makerlogTitle": "",
    "makerlogPreviewtext": "",
    "makerlogLink": "",
    "profileImg": "https://assets.disquiet.io/images/profile/6c6caae673b3f07dd2122d7520566a49d7d2f5a7ca42bdabd97a17f55f2bfba2",
    "profileName": "스티비",
    "profileRole": "이메일 뉴스레터 서비스@스티비",
    "profileLink": "https://disquiet.io/@stibee?utm_source=makerkit",
    "productLink": "https://disquiet.io/product/%EC%8A%A4%ED%8B%B0%EB%B9%84?utm_source=makerkit",
    "tallyLink": "https://tally.so/r/3yPG5B",
    "popularity": ""
  },
  {
    "productId": 11,
    "productName": "슈퍼코더",
    "productPreview": "해외개발자 채용 플랫폼",
    "benefitPreview": "할인 혜택(1회 매칭 fee 20% → 15%, 매월 관리 fee 10% → 7%)",
    "tag1": "🧑‍💻 개발툴",
    "tag2": "🏘 커뮤니티",
    "tag3": "📡 중개 플랫폼",
    "productDetail": "세컨드팀 (supercoder.co)은 개발자 채용에 어려움을 겪고 있는 기업들에게 개발자 역량 검증 및 국내&해외 개발자 채용 서비스를 제공하고 있는 Tech HR 스타트업입니다. 이로써 보다 글로벌하고 효과적인 개발 조직을 구축하실 수 있도록 도와드리고 있습니다. 현재 국내 tech 기업들의 고질적인 개발자 채용 문제를 우리만의 창의적인 방법으로 해결해 오고 있으며, 현재 top-tier 테크 기업에서 경험을 쌓은 co-founder 3명이 ‘개발자 역량 검증’, ‘단기 채용’, ‘장기 채용’ 세가지 서비스를 개발/운영 중입니다.",
    "benefitDetail": "할인 혜택을 제공하려 합니다.<br>기존에 저희가 고객사들에게 받는 수수료가 두 가지 종류가 있습니다.<br>1) One-time matching fee (최초 1회성)<br>2) Monthly management fee (매달 발생하는 비용)<br><br>1)의 경우 기존에는 저희를 통해 채용되는 개발자 분의 연봉의 20%,<br>2)의 경우 기존에는 개발자 분의 월급의 10%를 청구하게 되는데요.<br><br>디스콰이엇을 통해서 저희에게 연락 주시는 분들은 1)을 15%로 2)을 7%로 할인 드릴 예정입니다.",
    "isMakerlog": 1,
    "makerlogTitle": "시드 투자 유치 경험",
    "makerlogPreviewtext": "슈퍼코더 서비스를 만들고 있는 세컨드팀의 시드투자 유치 이야기를 적어보려고 합니다. 우선 저희 회사의 간략한 background 정보를 알려드리자면 세컨드팀은 창업한지 6개월 된 극초기 스타트업이고 슈퍼코더 서비스를 운영한지는 3개월 정도가 되어갑니다. 결론부터 말씀드리자면...",
    "makerlogLink": "https://disquiet.io/@kyle/makerlog/46?utm_source=makerkit",
    "profileImg": "https://assets.disquiet.io/images/profile/eb3e012338c2935543545714bcae46a56b8d0a4af007b35fa006c11da5f9ec11",
    "profileName": "정태헌",
    "profileRole": "CSO @Supercoder",
    "profileLink": "https://disquiet.io/@tjeong?utm_source=makerkit",
    "productLink": "https://disquiet.io/product/%EC%8A%88%ED%8D%BC%EC%BD%94%EB%8D%94?utm_source=makerkit",
    "tallyLink": "https://tally.so/r/3yPG5B",
    "popularity": ""
  },
  {
    "productId": 12,
    "productName": "되는시간",
    "productPreview": "되는시간 - 내가 되는 시간을 <br> 상대방이 예약할 수 있어요.",
    "benefitPreview": "무료 1개월 사용권",
    "tag1": "💸 세일즈",
    "tag2": "💻 노코드",
    "tag3": "🚲 생산성",
    "productDetail": "내가 되는 시간을 상대방이 예약할 수 있어요.<br><br>팀소개<br>- 저희는 초중고 동창으로 이루어진 팀입니다.<br>- 오랫동안 연락 안하고 지내다가 우연히 스타트업에서 만났습니다!",
    "benefitDetail": "무료 1개월 사용권",
    "isMakerlog": 1,
    "makerlogTitle": "SaaS 랜딩 페이지 전환율 공부",
    "makerlogPreviewtext": "되는시간 (https://whattime.co.kr) 서비스를 만들고 있는 김재영입니다. 주기적으로 서비스 퍼널을 분석 하며 서비스를 개선해 나가고 있는데요, 부족하지만 해당 내용 공유해 드립니다. 많은 서비스가 그렇듯 왜 가입자 수가 확 늘지 않을까 하는 고민을...",
    "makerlogLink": "https://disquiet.io/@whattime-jay/makerlog/1008?utm_source=makerkit",
    "profileImg": "https://assets.disquiet.io/images/profile/be7ace368088c5f2e787da46878215b1e81421664e8539e1d31d12668f487702",
    "profileName": "Hanna Oh",
    "profileRole": "되는시간 Co-founder&COO @왓타임",
    "profileLink": "https://disquiet.io/@jane6966?utm_source=makerkit",
    "productLink": "https://disquiet.io/product/%EB%90%98%EB%8A%94%EC%8B%9C%EA%B0%84-1644990364167?utm_source=makerkit",
    "tallyLink": "https://tally.so/r/3yPG5B",
    "popularity": ""
  },
  {
    "productId": 13,
    "productName": "셀렉트 Select",
    "productPreview": "스타트업을 위한 어드민, <br> 백오피스 솔루션",
    "benefitPreview": "크레딧 제공 <br> & 관리자 페이지 5개 제작 지원",
    "tag1": "🧑‍💻 개발툴",
    "tag2": "💻 노코드",
    "tag3": "🚲 생산성",
    "productDetail": "개발팀 입장에서는 제품 개선하기도 바쁜데 어드민까지 만들어야하고<br>운영팀은 백오피스 기능에 대한 니즈가 높지만 포기할 수 밖에 없는 아쉬운 상황이었는데요.<br><br>기존의 어드민 개발 방식보다 더 나은 방법이 필요하다고 생각했습니다.<br><br>이를 해결하고자 '셀렉트'는 어드민을 10배 더 쉽게 만들 수 있는 솔루션을 제공합니다.<br>☑️ 기존에 사용하던 SQL 쿼리, HTTP API 호출정보가 어드민이 됩니다.<br>☑️ 별도의 UI, 백엔드 개발이 필요하지 않습니다.<br>☑️ 어드민에서 자주 사용하는 기능을 빌트인으로 제공합니다.<br>(구글 로그인, 구글 시트로 내보내기 등)",
    "benefitDetail": "- 60만원 상당의 크레딧 제공<br>- 관리자 페이지 5개 제작 지원",
    "isMakerlog": 0,
    "makerlogTitle": "",
    "makerlogPreviewtext": "",
    "makerlogLink": "",
    "profileImg": "https://assets.disquiet.io/images/profile/5c13a3b756d05154579dec9df13202305afeefb3adad3a4c7c6091a870be3fd0",
    "profileName": "김학범",
    "profileRole": "제품 매니저 @셀렉트",
    "profileLink": "https://disquiet.io/@hkim?utm_source=makerkit",
    "productLink": "https://disquiet.io/product/%EC%85%80%EB%A0%89%ED%8A%B8-select?utm_source=makerkit",
    "tallyLink": "https://tally.so/r/3yPG5B",
    "popularity": ""
  },
  {
    "productId": 14,
    "productName": "스타우터",
    "productPreview": "IT 스타터를 위한 모든 것!",
    "benefitPreview": "IT 서비스 제작 가이드 및 <br> 템플릿 무료 제공",
    "tag1": "🎨 디자인",
    "tag2": "🚲 생산성",
    "tag3": "✏️ 교육",
    "productDetail": "4년간 IT 서비스의 기획&디자인&개발 모든 과정을 함께한 에이전시 Tirrilee가<br>초기 서비스 제작자 분들을 위해 새로운 서비스를 시작합니다 🥳<br><br>🌈 스타우터 MVP 테스트 진행중! 아래의 결과 자료를 무료로 받아보세요!<br>1️⃣ 기능 요구사항 정의서<br>2️⃣ 기능 구조도<br>3️⃣ 기능 별 예시화면<br>4️⃣ 초기 기획 가이드<br>5️⃣ 초기 기획서 양식",
    "benefitDetail": "- IT 서비스 제작 가이드 및 템플릿 무료 제공<br>- 기능 요구사항 정의서 작성<br>- 기능 구조도<br>- 기능 별 예시화면 제공",
    "isMakerlog": 0,
    "makerlogTitle": "",
    "makerlogPreviewtext": "",
    "makerlogLink": "",
    "profileImg": "https://assets.disquiet.io/images/profile/fbd0ffd8faa00dee6b3144129da279db3bde4e17b2a865f7171e48b32abc1881",
    "profileName": "스타우터",
    "profileRole": "PO ・ UXUI Design ・Developer @스타우터",
    "profileLink": "https://disquiet.io/@stauter?utm_source=makerkit",
    "productLink": "https://disquiet.io/product/스타우터/?utm_source=makerkit",
    "tallyLink": "https://tally.so/r/3yPG5B",
    "popularity": 4
  },
  {
    "productId": 15,
    "productName": "Outcode",
    "productPreview": "문서작성처럼 쉽고 빠르게 업무툴 만들기. Develop-on-Doc.",
    "benefitPreview": "할인 혜택 & 온라인/오프라인 <br> 온보딩 제공",
    "tag1": "🧑‍💻 개발툴",
    "tag2": "💻 노코드",
    "tag3": "🚲 생산성",
    "productDetail": "우리 팀 업무에 딱 맞는 업무툴은 어디 없을까요? 원하는 대로 바로바로, 쉽게 업무툴을 만들어 쓸 수 있다면 얼마나 좋을까요?<br><br>문서를 작성하듯이 쉽게, 가장 친숙한 방법으로 시작하세요. 나머지는 아웃코드가 책임집니다!",
    "benefitDetail": "디스콰이엇을 통해 신청해주신 분들께는 할인 혜택과 온라인/오프라인 온보딩을 제공할 예정입니다.",
    "isMakerlog": 1,
    "makerlogTitle": "아웃코드를 시작한 이유",
    "makerlogPreviewtext": "아웃코드팀은 일반 사용자를 위한 가장 심플하고 새로운 데이터 자동화 플랫폼을 만들고 있습니다. 우리의 미션은 전문지식이 없이도, 개발자가 아니어도 데이터를 쉽게 사용할 수 있도록 하는 것입니다. 우리가 개발하는 플랫폼인 아웃코드는 회사에서 쌓여가는 데이터를 누구나 쉽게 사용하기 위해 코드, 쿼리, 스크립트, 심지어 워크플로우까지 필요없는 새로운 형태의 가장 쉬운 경험을 제공하려고...",
    "makerlogLink": "https://disquiet.io/@outcode/makerlog/1922?utm_source=makerkit",
    "profileImg": "https://assets.disquiet.io/images/profile/fdbe47ee97fbd45afb32e2b15438f39ef73acafc5d8942941bead250337a0ad8",
    "profileName": "Lea Lim",
    "profileRole": "마케팅 @아웃코드",
    "profileLink": "https://disquiet.io/@lea_at_outcode?utm_source=makerkit",
    "productLink": "https://disquiet.io/product/outcode?utm_source=makerkit",
    "tallyLink": "https://tally.so/r/3yPG5B",
    "popularity": ""
  },
  {
    "productId": 16,
    "productName": "클랩CLAP",
    "productPreview": "팀 피드백 문화를 도와주는 솔루션",
    "benefitPreview": "20개 기업 한정으로 <br> 조직 문화 진단을 제공",
    "tag1": "🚲 생산성",
    "tag2": "🎙 미디어",
    "tag3": "",
    "productDetail": "팀 성장을 위한 피드백 문화의 시작 CLAP<br>CLAP을 통해 팀과 팀원의 성장을 돕고 지속적인 피드백을 할 수 있는 환경을 만들어보세요!<br><br>👏🏻CLAP 어떤 서비스를 제공하나요?<br>클랩은 조직과 구성원의 성장 및 이를 위한 피드백 문화 정착을 지원하는 다양한 기능이 준비되어 있습니다.",
    "benefitDetail": "- 키트 신청 혜택<br>디스콰이엇을 통해 클랩 연간 결제를 해주신 분들께는 클랩 서비스 사용 외에, 20개 기업 한정으로 조직 문화 진단 설문을 제공드려요!<br>- 효과<br>현재 회사에 존재하는 제도와 문화 중 구성원들의 생각과 차이를 파악할 수 있고 효과가 미비한 부분을 사전에 확인 후 개선시킬 수 있습니다.<br>- 신청 프로세스<br>1)메이커키트를 통해 클랩 사용을 신청해 주세요!<br>2)확인 후 담당 매니저가 1주일 이내 무료체험 연락을 드려요.<br>3)무료체험 기간이 종료되셨다면, 클랩 연간결제를 신청해 주세요!<br>4)디스콰이엇을 통해 연간결제를 하신 20인 한정으로<br>2주 내 조직문화 진단 설문조사를 전달드려요<br>5)전달드린 조직 문화 진단 설문조사를 작성 후 제출해 주세요!<br>6)제출이 종료되면, 확인 후 조직 문화 진단 결과를 전달드려요.<br><br>자세한 내용은 아래 링크를 참고해 주세요!<br><a href='https://bit.ly/disquiet_maker-kit'>https://bit.ly/disquiet_maker-kit</a>",
    "isMakerlog": 0,
    "makerlogTitle": "",
    "makerlogPreviewtext": "",
    "makerlogLink": "",
    "profileImg": "https://assets.disquiet.io/images/profile/32d788754ccafcf0792d37bc46191820bf4846fb9ebec9c6efe6f05d88c199d7",
    "profileName": "한혜민",
    "profileRole": "마케팅@디웨일",
    "profileLink": "https://disquiet.io/@dwhale_hyem?utm_source=makerkit",
    "productLink": "https://disquiet.io/product/clap?utm_source=makerkit",
    "tallyLink": "https://tally.so/r/3yPG5B",
    "popularity": 1
  },
  {
    "productId": 17,
    "productName": "슬리드",
    "productPreview": "동영상 학습에 최적화된 필기 노트",
    "benefitPreview": "프리미엄 회원권 1년권 <br> & 크리에이터 지원",
    "tag1": "🚲 생산성",
    "tag2": "✏️ 교육",
    "tag3": "",
    "productDetail": "영상 속 지식을 내 것으로, 슬리드'<br><br>슬리드는 유튜브, 온라인 클래스, 줌 등 동영상을 보는 동시에 쉽게 화면을 캡쳐하며 필기를 남길 수 있는 영상에 최적화된 노트 툴입니다.",
    "benefitDetail": "- 슬리드 프리미엄 회원권 1년권 (13만원 상당)<br>- 슬리드 크리에이터 지원 가능<br>- (슬리드 크리에이터 지원시) 슬리드 대표와의 1대1 온보딩 및 AMA 세션",
    "isMakerlog": 1,
    "makerlogTitle": "정현의 슬리드 노트 모아보기",
    "makerlogPreviewtext": "제가 공유한 노트들이 도움이 된다는 분들이 많으셔서, 그동안 작성한 노트를 모아볼 수 있는 슬리드 프로필 페이지를 만들었습니다.",
    "makerlogLink": "https://disquiet.io/@junghyun/makerlog/1490?utm_source=makerkit",
    "profileImg": "https://assets.disquiet.io/images/profile/d4435e14e0ddeadcf4e771d301cb9cf714481647ce920d1dc03e821a765a1f8d",
    "profileName": "Junghyun Park",
    "profileRole": "CEO @슬리드",
    "profileLink": "https://disquiet.io/@junghyun?utm_source=makerkit",
    "productLink": "https://disquiet.io/product/슬리드/?utm_source=makerkit",
    "tallyLink": "https://tally.so/r/3yPG5B",
    "popularity": 1
  },
  {
    "productId": 18,
    "productName": "미라클나잇",
    "productPreview": "고농축 슬립샷으로<br>세계 최고의 수면을 경험하다",
    "benefitPreview": "무료이용권 15개",
    "tag1": "🏃 헬스케어",
    "tag2": "🤖 인공지능",
    "tag3": "📷 라이프스타일",
    "productDetail": "피로회복을 위한 최적의 수면 사이클을 유도하는 인공지능 수면 유도 기술로 나에게 딱 맞는 수면 솔루션을 경험하세요!",
    "benefitDetail": "디스콰이엇 메어커분들께 15개의 무료이용권 제공해드릴 수 있습니다!",
    "isMakerlog": 1,
    "makerlogTitle": "🐋 3번의 실패 끝에 성공한 MVP 테스트",
    "makerlogPreviewtext": "우리 팀은 수면 문제를 해결하는 팀이다. 어떻게 하면 더 좋은 수면 솔루션으로 시장에 혁신을 가져올 것인지 고민했다. 오늘 글에서는 지난 1년간 우리 팀이 어떻게 실패했는지, 그리고 지금은 그 실패를 토대로 어떤 프로덕트를 고도화해나가고 있는지 이야기해보고자 한다.",
    "makerlogLink": "https://disquiet.io/@shawnice/makerlog/1958?utm_source=makerkit",
    "profileImg": "https://assets.disquiet.io/images/profile/ee9a795cf2797d1356f8778a609d90a43f0c97b098892f24eb5a07d7de50acdf",
    "profileName": "Shawny Kwon",
    "profileRole": "CEO @Munice Inc.",
    "profileLink": "https://disquiet.io/@shawnice?utm_source=makerkit",
    "productLink": "https://disquiet.io/product/%EB%AF%B8%EB%9D%BC%ED%81%B4%EB%82%98%EC%9E%87?utm_source=makerkit",
    "tallyLink": "https://tally.so/r/3yPG5B",
    "popularity": 4
  },
  {
    "productId": 19,
    "productName": "매치드",
    "productPreview": "결재자 기반 B2B 영업 매칭 서비스",
    "benefitPreview": "즉시 매칭이 가능한 메시지 발송권<br>주 2회 -> 주 5회 추가 제공",
    "tag1": "💸 세일즈",
    "tag2": "🚲 생산성",
    "tag3": "📡 중개 플랫폼",
    "productDetail": "⭐️매치드는 국내 최초 사전 심사제로 운영되는 결재자 기반 B2B 영업 매칭 서비스입니다.<br>심사를 통과한 기업의 의사결정권을 가지고 있는 결재자끼리의 매칭에 의해 다양한 기업 과제를 해결할 수 있으며, 비대면 시대에 적합하도록 온라인상에서 이루어지기 때문에 간편하게 영업 매칭이 가능합니다.",
    "benefitDetail": "모든 기능이 기본적으로 무료<br>즉시 매칭이 가능한 메시지 발송권 주 2회 -> 주 5회 추가 제공<br>* 참고 : 저희 매치드는 \"\"의사결정권자 기반 B2B매칭 플랫폼\"\"이고, 현재는 모든 기능 무료입니다.<br>매칭할 수 있는 메시지 발송권이 주 2회로 제한되게 주어지나, 이를 주 5회 부여로 혜택을 드리겠습니다.",
    "isMakerlog": 1,
    "makerlogTitle": "의사결정권자 B2B 매칭 '매치드' 공식오픈 했어요 :)",
    "makerlogPreviewtext": "B2B 영업 시, 의사결정권자와 다이렉트로 컨택이 가능하다면? 그래서 저희가 '매치드'를 만들었습니다.베타테스트를 통해서 소중한 피드백을 얻을 수 있었고, 무엇보다 좋았던건 'B2B 영업 툴로써 정말 필요했다', '잘 발전되었으면 좋겠다', 라는 진심어린 응원의 피드백 이었던것 같네요. 결코 우리가 틀린짓을 하고 있는건 아니구나 라는 생각을 하고 있습니다 :)",
    "makerlogLink": "https://disquiet.io/@matched_hhlee/makerlog/1355?utm_source=makerkit",
    "profileImg": "https://assets.disquiet.io/images/profile/79a7e940fe59eaba53172f552c096c94cbbae4e3bf55c5fb35bbfb80a40f94f2",
    "profileName": "이형호",
    "profileRole": "Leader @매치드",
    "profileLink": "https://disquiet.io/@matched_hhlee?utm_source=makerkit",
    "productLink": "https://disquiet.io/product/%EB%A7%A4%EC%B9%98%EB%93%9C?utm_source=makerkit",
    "tallyLink": "https://tally.so/r/3yPG5B",
    "popularity": ""
  },
  {
    "productId": 20,
    "productName": "STEAD",
    "productPreview": "채용을 더 쉽고 간편하게, 채용협업툴 스테드",
    "benefitPreview": "1년간 20% 할인 제공",
    "tag1": "🤖 인공지능",
    "tag2": "🚲 생산성",
    "tag3": "",
    "productDetail": "채용업무를 더 쉽고 간편하기위한 채용협업툴 스테드입니다:)<br>채용팀과 함께 지원자를 관리/평가하고 손쉽게 면접일정을 약속하여<br>채용업무의 생산성을 높여주는 다양한 기능들을 제공하고있습니다!",
    "benefitDetail": "1년간 20% 할인 제공",
    "isMakerlog": 0,
    "makerlogTitle": "",
    "makerlogPreviewtext": "",
    "makerlogLink": "",
    "profileImg": "https://assets.disquiet.io/images/profile/bd15356e5715115063a579739a5c5cbeb8ef9aaf3005e2abbf1710e97ec4c192",
    "profileName": "김범수",
    "profileRole": "대표 @(주)풀랩",
    "profileLink": "https://disquiet.io/@steadhr?utm_source=makerkit",
    "productLink": "https://disquiet.io/product/stead?utm_source=makerkit",
    "tallyLink": "https://tally.so/r/3yPG5B",
    "popularity": ""
  },
  {
    "productId": 21,
    "productName": "Figma CLI by Grida",
    "productPreview": "$ grida add 'https://figma.com/file/xxx'",
    "benefitPreview": "2인 이하 팀, 학생 대상 무료 제공",
    "tag1": "🧑‍💻 개발툴",
    "tag2": "🎨 디자인",
    "tag3": "💻 노코드",
    "productDetail": "Free & Open source - Design to Code 툴인 Grida 의 새로운 DX, Grida CLI 를 소개합니다.",
    "benefitDetail": "2인 이하 팀, 학생 대상 무료 제공",
    "isMakerlog": 0,
    "makerlogTitle": "",
    "makerlogPreviewtext": "",
    "makerlogLink": "",
    "profileImg": "https://assets.disquiet.io/images/profile/0fc2e10c099707cd5c2e04b156e574e2d7c4d1b050e24b9de4ba3adfc4fa6ee3",
    "profileName": "Universe",
    "profileRole": "Founder & CEO @grida.co",
    "profileLink": "https://disquiet.io/@universe?utm_source=makerkit",
    "productLink": "https://disquiet.io/product/figma-cli-by-grida?utm_source=makerkit",
    "tallyLink": "https://tally.so/r/3yPG5B",
    "popularity": ""
  },
  {
    "productId": 22,
    "productName": "Tape",
    "productPreview": "팀을 위한 Video Messaging!",
    "benefitPreview": "온/오프라인 온보딩 & 유료 요금제 출시 후 할인/이용권 제공",
    "tag1": "🚲 생산성",
    "tag2": "🎙 미디어",
    "tag3": "",
    "productDetail": "끝없는 메신저와 화상회의에서 당신의 하루를 지키기 위해 ✨Tape✨이 왔습니다.<br>Tape은 짧은 비디오를 녹화해 팀원과 대화할 수 있는 서비스입니다.<br>메신저로는 설명이 어려울 때, Zoom 미팅을 잡기 시작하는 대신 Tape을 보내보세요🤹‍♂️",
    "benefitDetail": "1. 디스콰이엇을 통해 신청해주신 분들께는 온라인/오프라인 온보딩을 제공하겠습니다! <br>2. 향후 유료 요금제 출시 시, 할인 또는 무료 이용권을 제공하겠습니다!",
    "isMakerlog": 0,
    "makerlogTitle": "",
    "makerlogPreviewtext": "",
    "makerlogLink": "",
    "profileImg": "https://assets.disquiet.io/images/profile/c453fad09fd0b3d839e8311881d4dc019e1efc53fd481b84140944423d9758e6",
    "profileName": "송정진",
    "profileRole": "Frontman @Taper Labs",
    "profileLink": "https://disquiet.io/@jaythesong?utm_source=makerkit",
    "productLink": "https://disquiet.io/product/tape?utm_source=makerkit",
    "tallyLink": "https://tally.so/r/3yPG5B",
    "popularity": ""
  },
  {
    "productId": 23,
    "productName": "콘티고",
    "productPreview": "AI 기반의 모바일 인사관리 서비스",
    "benefitPreview": "크레딧 제공 - 3개월 무료 (기존 쿠폰과 별도) / 최대 6개월까지도 무료 사용 가능",
    "tag1": "🤖 인공지능",
    "tag2": "🚲 생산성",
    "tag3": "",
    "productDetail": "아직 인사담당자를 채용/지정하지 않아 직접 인사관리 업무를 처리해야 하는 창업가/대표를 위해 AI 파트너가 실시간으로 지원하는 모바일 인사관리 서비스입니다. [콘티고]를 이용해 고용계약, 근태관리, 급여관리, 구성원 코칭 및 사내 커뮤니케이션 등 필수적인 인사업무를 효율적으로 관리해 보세요.",
    "benefitDetail": "크레딧 제공 - 3개월 무료 (기존 쿠폰과 별도) / 최대 6개월까지도 무료 사용 가능",
    "isMakerlog": 1,
    "makerlogTitle": "초심 = 사용자 중심",
    "makerlogPreviewtext": "우리회사가 만들고 있는 콘티고는 스스로 인사관리를 할 수 밖에 없는 대표를 위한 AI 기반의 모바일 인사관리 서비스입니다. 딴에는 인사관리 업무에 대한 경험이나 이해가 부족할 대표들을 위한다고 필수적인 인사관리 업무로만 서비스를 구성하겠다, (rule base의 기초적인 수준이지만)AI 에이전트를 구현해서 업무에 누수가 발생하지 않도록 돕겠다, 자동화할 수 있는 업무는 최대한 자동화하겠다... 는 기조로 서비스를 디자인했다 생각했죠.",
    "makerlogLink": "https://disquiet.io/@anakin/makerlog/1393?utm_source=makerkit",
    "profileImg": "https://assets.disquiet.io/images/profile/6c5fe4bf930c2e04ec9b6981c489dc849db583d3fcb0c4b502914fbe77233cf6",
    "profileName": "LEO",
    "profileRole": "기획 @주식회사 콘티고",
    "profileLink": "https://disquiet.io/@leo365?utm_source=makerkit",
    "productLink": "https://disquiet.io/product/%EC%BD%98%ED%8B%B0%EA%B3%A0?utm_source=makerkit",
    "tallyLink": "https://tally.so/r/3yPG5B",
    "popularity": ""
  },
  {
    "productId": 24,
    "productName": "mmhmm",
    "productPreview": "이제 미팅은 그만, 녹화된 영상으로<br>커뮤니케이션에 슈퍼파워를!",
    "benefitPreview": "1개월 무료 프리미엄",
    "tag1": "🚲 생산성",
    "tag2": "✏️ 교육",
    "tag3": "🎙 미디어",
    "productDetail": "코로나 이후로 많은 미팅이 온라인으로 전환되었어요. 그 때문인지 미팅은 더 늘었고, 하루에도 수많은 내부, 외부 미팅을 소화해야합니다. 소통은 더욱 불편해졌고 집중할 수 있는 시간은 줄어들었어요.",
    "benefitDetail": "1개월 무료 프리미엄",
    "isMakerlog": 0,
    "makerlogTitle": "",
    "makerlogPreviewtext": "",
    "makerlogLink": "",
    "profileImg": "https://assets.disquiet.io/images/profile/623b744abc9c7d78085f71057101e52f81e76f54766c2a3dbc6c1eddf26413f6",
    "profileName": "진대연",
    "profileRole": "사업개발 @mmhmm @당근메일",
    "profileLink": "https://disquiet.io/@dave?utm_source=makerkit",
    "productLink": "https://disquiet.io/product/mmhmm?utm_source=makerkit",
    "tallyLink": "https://tally.so/r/3yPG5B",
    "popularity": ""
  },
  {
    "productId": 25,
    "productName": "서플",
    "productPreview": "지하철 환경 기반<br>모바일 광고 콘텐츠 플랫폼",
    "benefitPreview": "광고 크레딧 지급 및 광고 혜택",
    "tag1": "🔮 마케팅툴",
    "tag2": "📷 라이프스타일",
    "tag3": "📡 중개 플랫폼",
    "productDetail": "서플은 새로운 광고문화를 위해 지하철 공간에 집중합니다!<br>지하철은 시선을 돌리지 않는 광고회피가 제한되는 공간입니다. 서플은 탑승 여부를 구분하고 이를 이용해 온전히 광고 콘텐츠에 집중할 수 있는 환경을 제공 합니다.",
    "benefitDetail": "서플의 4.5만 유저들을  클라이언트의 홈페이지 다이렉트 랜딩 서비스 제공<br>서플은 지하철과 버스 이용자들을 대상으로 모바일 광고콘텐츠를 제공하며 동영상과 홈페이지를 동시에 송출하여 제품의 정보전달력을 극대화 시키고 있습니다.<br>- 앱, 웹, 트레픽, 매출증대 솔루션<br><br>혜택<br>1. 디스콰이엇 메이커들에게는  유료광고진행시25% 광고 크레딧 추가 지급<br>2. 광고 진행시  앱 메인 배너 광고 1주일 무료제공<br>2. 무료 노출 광고 제공(맴버십)",
    "isMakerlog": 0,
    "makerlogTitle": "",
    "makerlogPreviewtext": "",
    "makerlogLink": "",
    "profileImg": "https://assets.disquiet.io/images/profile/8c55943de424627d34bfe8cdf910575a862ffae32060e8e5a851b12485eaec03",
    "profileName": "나현석",
    "profileRole": "Co-founder @서플",
    "profileLink": "https://disquiet.io/@subple?utm_source=makerkit",
    "productLink": "https://disquiet.io/product/서플?utm_source=makerkit",
    "tallyLink": "https://tally.so/r/3yPG5B",
    "popularity": ""
  },
  {
    "productId": 26,
    "productName": "effi.io",
    "productPreview": "버그리포팅 • 디자인 QA가<br>놀랍도록 간편해집니다",
    "benefitPreview": "러쉬 요금제 6개월간 무료",
    "tag1": "🎮 게임",
    "tag2": "🎨 디자인",
    "tag3": "🚲 생산성",
    "productDetail": "버그 리포팅 • 디자인 QA는 원래 이랬어야죠.  ✔️동영상 / 이미지에 손쉽게 이슈영역을 표시하여 전달할 수 있어요. (홈페이지에서 체험모드 제공) ✔️모바일 스크린샷을 간편하게 effi웹으로 불러와서 커멘트할 수 있어요. ✔️JIRA와의 완벽한 양방향 싱크(댓글/내용수정도 싱크) ✔️기기명과 OS버전을 자동으로 기록해 드려요. ✔️여러 테스트빌드를 올리고 다운받을 수 있는 페이지를 제공해 드려요.",
    "benefitDetail": "디스콰이엇을 통해 effi.io를 시작하시는 분께는 러쉬 요금제까지 6개월간 무료로 제공해드립니다($600 상당)🎅👍",
    "isMakerlog": 0,
    "makerlogTitle": "",
    "makerlogPreviewtext": "",
    "makerlogLink": "",
    "profileImg": "https://assets.disquiet.io/images/profile/cd6d6975cbffa2f7d18e0b785b03324afd6ef4337ee0588bdc51698950ebac28",
    "profileName": "최동규",
    "profileRole": "PM @effi.co",
    "profileLink": "https://disquiet.io/@dgchoi",
    "productLink": "https://disquiet.io/product/effi",
    "tallyLink": "https://tally.so/r/3yPG5B",
    "popularity": ""
  },
  {
    "productId": 27,
    "productName": "땡쓰",
    "productPreview": "B2B 급여 선지급 서비스",
    "benefitPreview": "가입 즉시 사용 가능 한도 1000만원 지원, <br> 3개월 동안 수수료 없이 무료로 사용 가능",
    "tag1": "💰 금융",
    "tag2": "📷 라이프스타일",
    "tag3": "",
    "productDetail": "안녕하세요, 신개념 금융복지 서비스 '땡쓰' 입니다. <br> '땡쓰'와의 제휴를 통해 일한만큼 원하는 날 원하는 만큼 급여를 받을 수 있는 생활이 시작됩니다.\n\n변화하는 시대, 탄력적으로 근무 하는데, 왜 탄력적으로 급여를 받을 수는 없을까요?<br>이러한 고민에서 시작해, 월급 받는 즐거움을 한 달에 한 번이 아닌, 원하는 만큼 얻을 수 있게 하는 서비스를 만들었습니다.<br>한 달에 최대 급여의 50%까지 땡겨쓰기가 가능하며, 건강보험조회를 통해 자동으로 근무정보가 책정됩니다.",
    "benefitDetail": "1. 가입 즉시 사용 가능 한도 1000만원 지원 <br> 2. 3개월 동안 수수료 없이 무료로 사용 가능",
    "isMakerlog": 0,
    "makerlogTitle": "",
    "makerlogPreviewtext": "",
    "makerlogLink": "",
    "profileImg": "https://assets.disquiet.io/images/profile/e62aa2fef4e1361fd41d37c951ef2ba2fbd99c20d8bf568db34dcfd579631865",
    "profileName": "Reen",
    "profileRole": "마케터 @주식회사 기빙데이즈",
    "profileLink": "https://disquiet.io/@leehreen?utm_source=makerkit",
    "productLink": "https://disquiet.io/product/%EB%95%A1%EC%93%B0?utm_source=makerkit",
    "tallyLink": "https://tally.so/r/3yPG5B",
    "popularity": ""
  },
  {
    "productId": 28,
    "productName": "서베이지",
    "productPreview": "대학(원)생을 위한 서베이 플랫폼<br>서베이를 이지하게!",
    "benefitPreview": "10% 할인 혜택 제공",
    "tag1": "✏️ 교육",
    "tag2": "👫 소셜",
    "tag3": "",
    "productDetail": "대학(원)생의 설문조사 제작, 배포 과정의 불편함과 어려움을 해결하는 '서베이지'입니다.<br>✅ 설문 응답 서비스: 설문조사를 제작한 후, 설문에 응답해줄 사람을 구하는 배포 과정에 어려움을 겪는 분들을 위해, 서베이지 패널이 항상 대기 중입니다!<br>✅ 설문 템플릿: Google Form을 이용한 설문조사 제작이 어려운 분들을 위해, (1) 사용경험 설문조사, (2) 인식 설문조사 템플릿을 배포합니다. (웹사이트 오픈 기념, 무료!)",
    "benefitDetail": "서베이지의 1) 설문 응답 서비스, 2) 인터뷰 중개 서비스, 3) 베타테스터 모집 서비스를 이용하고 싶은 분들께 디스콰이엇 전용 쿠폰 발행을 통해 10% 할인 혜택을 제공해드리겠습니다! (24시간 응대를 도와드리고 있으니, 편하게 문의 주세요!)",
    "isMakerlog": 1,
    "makerlogTitle": "2022 상반기 팀 회고 - 서베이지",
    "makerlogPreviewtext": "최소 6개월에 한번씩은 팀이 다같이 하루종일 그간 했던 활동과 성과를 돌아보고, 배우고 느낀 점을 공유하는 시간을 가지는 것이 좋다고 생각해요 (하반기부터는 분기별로 해볼까 생각 중입니다) 그래서 7월 1일, 팀원들과 다함께 상반기 회고를 진행했고 해당 내용을 메이커로그로 남겨보려 합니다. 글을 쓰기 전, 문득 떠올라 연초에 썼던 2021년 회고 글을 다시 읽어보니 감회가 새롭네요.",
    "makerlogLink": "https://disquiet.io/@songforefa/makerlog/1018?utm_source=makerkit",
    "profileImg": "https://assets.disquiet.io/images/profile/12c5a61975a35c7f1b8f40e802240b04a2111c9cb174bd268ce33d841a1c91aa",
    "profileName": "송다예 Daye Song",
    "profileRole": "CEO @턴업컴퍼니 (서베이지, 렛츠인턴)",
    "profileLink": "https://disquiet.io/@songforefa?utm_source=makerkit",
    "productLink": "https://disquiet.io/product/%EC%84%9C%EB%B2%A0%EC%9D%B4%EC%A7%80-surveasy?utm_source=makerkit",
    "tallyLink": "https://tally.so/r/3yPG5B",
    "popularity": ""
  },
  {
    "productId": 29,
    "productName": "엑소스피어",
    "productPreview": "SaaS형 올인원 PC보안 서비스<br>(PC백신+정보유출예방)",
    "benefitPreview": "무료 기업용 PC백신 제공<br> 온라인 데모 신청 시 사은품 혜택",
    "tag1": "📊 분석툴",
    "tag2": "🚲 생산성",
    "tag3": "🔒 보안",
    "productDetail": "1. 🛡️ 국내 유일 올인원 보안 서비스 <br>국내에서 유일하게 기업용 PC백신과 정보유출예방(DLP)을 하나의 에이전트로 제공합니다. 또한, macOS를 지원해서 하나의 PC보안 서비스로 사내 보안 설계를 끝낼 수 있습니다!<br>2. 💸 국내 유일 무료 기업용 PC백신<br>여러분은 기업에서 개인용 백신을 사용하는 것이 불법임을 알고 계신가요? 엑소스피어는 모든 기업이 최소한의 정보보안 시스템을 도입할 수 있도록 기업용 PC백신을 무료로 제공하고 있습니다.<br>3. 👨‍💼 보안 비전문가를 위한 보안 서비스<br>엑소스피어가 '보안 솔루션'이 아닌 '보안 서비스'인 이유는 강력한 보안 기능 위에 사용자 편의성을 추가했기 때문입니다. 엑소스피어의 개선된 UI/UX와 온라인 데모 + 실시간 보안 전문가 상담으로 누구나 사내 정보보안을 시작할 수 있습니다!<br>4. 💻 합리적인 SaaS 보안 서비스<br>엑소스피어는 동일 기능의 타사 서비스 대비 50% 이상 저렴한 비용으로 이용이 가능하며, SaaS 서비스 이기 때문에 도입과 해지가 당일 1~2시간 안에 완료 됩니다.",
    "benefitDetail": "1. 무제한 무료 기업용 PC백신 제공<br>2. 온라인 데모 신청 시 사은품 증정<br>3. 요청 시 유료플랜 1개월 체험권 증정",
    "isMakerlog": 0,
    "makerlogTitle": "",
    "makerlogPreviewtext": "",
    "makerlogLink": "",
    "profileImg": "https://assets.disquiet.io/images/profile/65f57b3b5fdc22c7c2ea8d1062ae0e9343443c532a5bc7f8afde090a15be982a",
    "profileName": "Changha Park",
    "profileRole": "마케팅 매니저 @엑소스피어",
    "profileLink": "https://disquiet.io/@len?utm_source=makerkit",
    "productLink": "https://disquiet.io/product/%EC%97%91%EC%86%8C%EC%8A%A4%ED%94%BC%EC%96%B4?utm_source=makerkit",
    "tallyLink": "https://tally.so/r/3yPG5B",
    "popularity": ""
  },
  {
    "productId": 30,
    "productName": "NIZ",
    "productPreview": "SNS와 커뮤니티에서 '키워드'로 데이터를 수집해 AI가 분석하는 소셜 모니터링 솔루션",
    "benefitPreview": "데모 계정, 2주 무료 체험 제공",
    "tag1": "🔮 마케팅툴",
    "tag2": "📊 분석툴",
    "tag3": "👫 소셜",
    "productDetail": "#NIZ는 SNS와 커뮤니티에서 '키워드'로 데이터를 수집해 AI가 '감정(긍정/부정/중립)'과 '카테고리(가격/서비스/디자인/품질/기타)'를 분석하여 시장이나 제품, 브랜드에 대한 고객 반응을 분석하는 소셜 모니터링 솔루션입니다.",
    "benefitDetail": "데모 계정, 2주 무료 체험 제공",
    "isMakerlog": 1,
    "makerlogTitle": "새롭게, 더 멋지게.. 드디어 완료!",
    "makerlogPreviewtext": "2019년 맥도날드의 SNS에서 발생하는 VOC를 수집/분석하는 목적으로 시작된 저희 서비스는 OB맥주와 오픈이노베이션이나, 삼쩜삼 등 2020년 당시 스타트업이나 많은 기업들에게 서비스를 제공하고, 많은 피드백을 받으며 제품 개선과 미래를 고민하고 있었습니다.\n\n하지만 스타트업 특성상 생존을 우선하여 외주 사업에 뛰어들었고, 이는 우리 제품 개발의 지연이라는 슬픈 결과로 이어지게 되었죠...\n\n그리고 내부적으로도 많은 변화를 거치고 난 후,우여곡절 끝에 1.0.0 버전이 업데이트 되었지만...\n\n생각만큼 만족스러운 결과가 나오지는 않았습니다.",
    "makerlogLink": "https://disquiet.io/@kaiden/makerlog/1902?utm_source=makerkit",
    "profileImg": "https://assets.disquiet.io/images/profile/f399ba0b6b9d2aa2836a439d7d014ed927a9929802b0bf43c34429db8f9bbd84",
    "profileName": "kaiden",
    "profileRole": "Sales @Mysterico",
    "profileLink": "https://disquiet.io/@kaiden?utm_source=makerkit",
    "productLink": "https://disquiet.io/product/niz?utm_source=makerkit",
    "tallyLink": "https://tally.so/r/3yPG5B",
    "popularity": ""
  },
  {
    "productId": 31,
    "productName": "페이플",
    "productPreview": "스타트업을 위한 PG(온라인결제)서비스를 제공하며, 다양한 스타트업과 상생하고 있습니다.",
    "benefitPreview": "페이플 가입비 면제 혜택 제공",
    "tag1": "💰 금융",
    "tag2": "",
    "tag3": "",
    "productDetail": "Payment Must Be Simple!\n페이플은 2018년 3월, 스타트업, 소상공인의 간편결제 서비스를 통해 전자결제시장을 혁신하고자 설립된 핀테크 스타트업입니다.\n\n> 초보개발자도 쉽고 편리하게 연동할 수 있는 간편결제서비스 제공\n> PG를 처음 도입하거나 PG변경을 위한 친절한 상담을 통해 최적의 선택을 하실 수 있도록 지원\n> 합리적인 수수료로 부담을 줄여 꿈을 이루고 있는 스타트업과의 상생\n\n페이플은 전자결제에 집중, 또 집중함으로써 매우 이례적으로 스타트업 최초로 금융위원회의 금융규제 샌드박스 “혁신금융서비스” 1호에 지정되어 간편출금 인증방식인 ‘SMS 출금인증방식’을 서비스 제공하고 있습니다.",
    "benefitDetail": "- 페이플 가입비 면제 혜택을 드립니다!! \n- 페이플 서비스를 이용하면 노션, AWS, 네이버 클라우드 크래딧 제공 등 추가 혜택이 있어요!",
    "isMakerlog": 0,
    "makerlogTitle": "",
    "makerlogPreviewtext": "",
    "makerlogLink": "",
    "profileImg": "https://assets.disquiet.io/images/profile/5421b09bec2de473e226fe6bbce1234e57becb8d87de84b5367520bc01a4e81d",
    "profileName": "페이플",
    "profileRole": "마케팅 @(주)페이플",
    "profileLink": "https://disquiet.io/@paypler?utm_source=makerkit",
    "productLink": "https://disquiet.io/product/%ED%8E%98%EC%9D%B4%ED%94%8C?utm_source=makerkit",
    "tallyLink": "https://tally.so/r/3yPG5B",
    "popularity": ""
  }
];