export default [
  {
    "productId": 1,
    "productName": "리스토베이",
    "productPreview": "쉽고 똑똑하게, 온라인 설문 제작 플랫폼",
    "benefitPreview": "스탠다드 결제 시 프리미엄으로 업그레이드 & 연결제 시 5% 할인",
    "tag1": "🔮 마케팅툴",
    "tag2": "📊 분석툴",
    "tag3": "💻 노코드",
    "productDetail": "리스토베이는 누구든지 쉽고 간편하게 설문을 제작하고, 다양한 방식으로 배포할 수 있으며 실시간으로 수집된 응답을 분석하여 리포트를 제공하는 온라인 설문 플랫폼입니다.",
    "benefitDetail": "스탠다드 결제 시 프리미엄으로 업그레이드 & 연결제 시 5% 할인",
    "isMakerlog": 0,
    "makerlogTitle": "",
    "makerlogPreviewtext": "",
    "makerlogLink": "",
    "profileImg": "https://assets.disquiet.io/images/profile/33dca4b1bb83f3aced14526e0810fc78946434516169e942c36400c5176fc94d",
    "profileName": "listovey",
    "profileRole": "CEO @Listovey",
    "profileLink": "https://disquiet.io/@listovey_platfrom",
    "productLink": "https://disquiet.io/product/%EB%A6%AC%EC%8A%A4%ED%86%A0%EB%B2%A0%EC%9D%B4",
    "tallyLink": "https://tally.so/r/3yPG5B",
    "popularity": 3
  },
  {
    "productId": 2,
    "productName": "도다",
    "productPreview": "응답하고 싶은 인터랙티브 폼",
    "benefitPreview": "무료 플랜 업그레이드 1개월 제공",
    "tag1": "🔮 마케팅툴",
    "tag2": "💻 노코드",
    "tag3": "🚲 생산성",
    "productDetail": "Into the Mind of Your Customer. 사람 중심으로, 쉽고 빠르게, 좋은 질문을 할 수 있는 서베이 폼 서비스입니다. 응답자 친화적인 UX와 몰입감을 자랑합니다.",
    "benefitDetail": "무료 플랜 업그레이드 1개월 제공",
    "isMakerlog": 1,
    "makerlogTitle": "드디어 한 방이 제대로 들어갔다.",
    "makerlogPreviewtext": "프리미엄 플랜의 2nd month retention이 14%나 올라갔다. HYBE가 작년 4월에 처음 우리 데모를 쓸 때가 생각난다. 1달 만에 만든 목업 데모를 돈주고 쓰겠다는 HYBE는 엄청난 기능 피드백을 줬고...",
    "makerlogLink": "https://disquiet.io/@doda_tool/makerlog/1047",
    "profileImg": "https://assets.disquiet.io/images/profile/1ae37579fe0ba6f80fff890ef3fb610ec533513aa8b43368ce468b1d0d8c6f46",
    "profileName": "곽도영",
    "profileRole": "CEO @(주)도다마인드",
    "profileLink": "https://disquiet.io/@doda_tool",
    "productLink": "https://disquiet.io/product/%EB%8F%84%EB%8B%A4-%ED%88%B4",
    "tallyLink": "https://tally.so/r/3yPG5B",
    "popularity": 2
  },
  {
    "productId": 3,
    "productName": "페넷 체커",
    "productPreview": "모바일 앱 취약점 자동 진단 엔진",
    "benefitPreview": "취약점 진단 결과에 대한 Private Q&A 세션 무료 제공",
    "tag1": "🧑‍💻 개발툴",
    "tag2": "📊 분석툴",
    "tag3": "🚲 생산성",
    "productDetail": "페넷은 어렵고 비싸다고 여겨지던 보안을 쉽고 간편하게 만듭니다! 화이트 해커가 직접 큐레이션한 진단 항목으로 앱의 보안 취약점을 쉽게 찾고 조치하세요!",
    "benefitDetail": "-페넷 체커를 통해 모바일 앱 취약점 진단 결과에 대한 Private Q&A 세션 무료 제공\n-정식 버전 출시(2023년 1월 예정) 이후, 이용 요금 할인 혜택 제공",
    "isMakerlog": 1,
    "makerlogTitle": "정보보안 비용을 15배 아끼는 방법",
    "makerlogPreviewtext": "오늘날 소프트웨어 개발 라이프 사이클(SDLC)은 크게 [요구사항수집 - 기획 - 개발(코딩) - 테스트 - 배포 - 유지보수]로 이루어져 있습니다. 소수의 인원으로 구성된 초기 스타트업은 테스트를 위한 QA인력을 별도로 구성하기 어려워...",
    "makerlogLink": "https://disquiet.io/@wonderz/makerlog/1249",
    "profileImg": "https://assets.disquiet.io/images/profile/220cd0163cb99a0e27bf35a181e8197087384d17789a2209abf45078b86b4ebc",
    "profileName": "김기명",
    "profileRole": "CEO @주식회사 월간해킹",
    "profileLink": "https://disquiet.io/@wonderz",
    "productLink": "https://disquiet.io/product/%ED%8E%98%EB%84%B7-%EC%B2%B4%EC%BB%A4",
    "tallyLink": "https://tally.so/r/3yPG5B",
    "popularity": 1
  },
  {
    "productId": 4,
    "productName": "애드샐러드",
    "productPreview": "트래킹 툴을 사용할 수 있도록 돕는 리타게팅 링크 서비스",
    "benefitPreview": "프리미엄 플랜 1개월 무료 혜택",
    "tag1": "🔮 마케팅툴",
    "tag2": "📊 분석툴",
    "tag3": "🚲 생산성",
    "productDetail": "리타게팅 링크를 생성하고 관리할 수 있는 리타게팅 링크 매니지먼트 서비스 '애드샐러드'입니다.\n\n스크립트 설치가 안되는 플랫폼에서도 픽셀 등의 트래킹 툴을 우회해서 사용할 수 있도록 돕는 마케팅 도구입니다. 링크 클릭 후 랜딩페이지로 유입되는 과정에서 스크립트가 동작하게 해 방문자 데이터를 수집, 분석하실 수 있습니다.",
    "benefitDetail": "프리미엄 플랜 1개월 무료 혜택",
    "isMakerlog": 1,
    "makerlogTitle": "노코드로 '실제 서비스 되는' 프로덕트를 만들 수 있을까?",
    "makerlogPreviewtext": "애드샐러드의 최초 프로덕트는 개발 외주로 제작된 것이었습니다. 기획을 들고 개발 전문사와 미팅 후 외주 비용을 치르고...",
    "makerlogLink": "https://disquiet.io/@hweedongs/makerlog/566",
    "profileImg": "https://assets.disquiet.io/images/profile/2e538a3da5a04979c32e062e6e0e7a45094431f62d897d37fdfe5a08c9dc9a14",
    "profileName": "하희철",
    "profileRole": "메이커 @놀라운형제들",
    "profileLink": "https://disquiet.io/@hweedongs",
    "productLink": "https://disquiet.io/product/%EC%95%A0%EB%93%9C%EC%83%90%EB%9F%AC%EB%93%9C",
    "tallyLink": "https://tally.so/r/3yPG5B",
    "popularity": ""
  },
  {
    "productId": 5,
    "productName": "Oopy. 우피",
    "productPreview": "노션을 이용한 노코드 웹페이지 빌더",
    "benefitPreview": "무료 체험 기간(1주일)동안 프로 플랜 사용",
    "tag1": "🔮 마케팅툴",
    "tag2": "💻 노코드",
    "tag3": "🚲 생산성",
    "productDetail": "노션을 이용해 웹페이지를 만드는데 필요한 2%를 제공하는 서비스입니다. 더 많은 분들이 쉽게 웹페이지를 만들고, 수정하고, 배포하고, 성장했으면 좋겠어요! 그러기 위해 필요한 부분을 언제나 듣고 싶습니다 :)",
    "benefitDetail": "무료 체험 기간(1주일)동안 프로 플랜 사용 가능하도록 할 수 있습니다. (현재 베이직 플랜만 무료 체험 가능)",
    "isMakerlog": 0,
    "makerlogTitle": "",
    "makerlogPreviewtext": "",
    "makerlogLink": "",
    "profileImg": "https://assets.disquiet.io/images/profile/4d14615ebca2d0a50fe0c00142c0cc5eb546507de1c685eda3be5ce112d8a5cc",
    "profileName": "최종욱",
    "profileRole": "Founder @Oopy",
    "profileLink": "https://disquiet.io/@johnwook",
    "productLink": "https://disquiet.io/product/oopy.-%EC%9A%B0%ED%94%BC",
    "tallyLink": "https://tally.so/r/3yPG5B",
    "popularity": ""
  },
  {
    "productId": 6,
    "productName": "센드타임",
    "productPreview": "B2B 비즈니스 미팅 스케줄링에는 sendtime! 😎",
    "benefitPreview": "개인 및 그룹 스케줄링 무제한 사용 + 무료 사용 기간을 기본 3개월",
    "tag1": "💸 세일즈",
    "tag2": "🚲 생산성",
    "tag3": "📷 라이프스타일",
    "productDetail": "🗣️ 시간 언제 괜찮으세요?\n👤 센드타임으로 조율할까요?\n\n📅 “조율은 빨리, 기회는 많이”\n스케줄링은 업무가 아니에요. 조율하는 시간을 다른 곳에 의미있게 사용하세요",
    "benefitDetail": "센드타임 유료화시, 디스콰이엇을 통해 들어오는 분들의 경우 \"개인 및 그룹 스케줄링\" 무제한 사용 + 무료 사용 기간을 기본 1개월을 \"3개월\"로 늘려드리고자 합니다 ✨",
    "isMakerlog": 1,
    "makerlogTitle": "Heading to San Francisco!✈️ 센드타임, 글로벌도 도전해보자!",
    "makerlogPreviewtext": "오늘부터 10일간 500 Global Founders Retreat 에 참여하게됩니다!\n\n정말 두근거리고, 스플랩/센드타임에게 글로벌 진출의 시작이 될 것만 같은 기분이 들어서 너무...",
    "makerlogLink": "https://disquiet.io/@splab_ceo/makerlog/1219",
    "profileImg": "https://assets.disquiet.io/images/profile/cc4dfc318e30f1e0ab89b9455a03372548e1b6444876777e88d118287155204f",
    "profileName": "선민승",
    "profileRole": "CEO @Splab Inc",
    "profileLink": "https://disquite.io/@splab_ceo",
    "productLink": "https://disquiet.io/product/%EC%84%BC%EB%93%9C%ED%83%80%EC%9E%84",
    "tallyLink": "https://tally.so/r/3yPG5B",
    "popularity": ""
  },
  {
    "productId": 7,
    "productName": "타입드",
    "productPreview": "지식관리 기반 문서 툴",
    "benefitPreview": "3개월 간 58% 월 구독료 할인",
    "tag1": "🚲 생산성",
    "tag2": "",
    "tag3": "",
    "productDetail": "왜 우리의 워드프로세스는 어떤 문서를 작성할 때, 내가 수집하고 조회하는 자료에는 무관심했을까요?\n작성하는 문서의 컨텍스트에 맞게 리소스를 쉽게 찾고, 심지어 추천 받아 활용 할 수 있다면 어떨까요?\n\n타입드(Typed)의 여정은 그러한 근본적인 질문에서 출발하였습니다.\nDoc, Ppt, Excel 등 기존에 사용하시는 문서 툴을 필요에 맞게 그대로 쓰시고,\n모든 리소스 관리와 추천은 타입드가 책임 집니다!",
    "benefitDetail": "3개월 간 58% 월 구독료 할인",
    "isMakerlog": 1,
    "makerlogTitle": "[성장하는 사람들과 하루하루 인생을 나아간다는 것]",
    "makerlogPreviewtext": "스타트업을 하다보면 정말 ‘짜릿'한 순간들도 종종 찾아오곤 하지만, 그러한 순간들은 잠깐 ‘반짝'하고 지나가 버리기 마련인 것 같아요.\n계속해서 더 큰 도전이 앞에 기다리고 있고, 예상치 못한 변수가 또 발생하기 마련이고…",
    "makerlogLink": "https://disquiet.io/@woojin_kim/makerlog/53",
    "profileImg": "https://assets.disquiet.io/images/profile/0d6581fc8377033ce511fda155076050ca235bd24beb145901b1484ecbf0fdf3",
    "profileName": "Woojin Kim",
    "profileRole": "CEO @비즈니스캔버스",
    "profileLink": "https://disquiet.io/@woojin_kim",
    "productLink": "https://disquiet.io/product/타입드/",
    "tallyLink": "https://tally.so/r/3yPG5B",
    "popularity": ""
  },
  {
    "productId": 8,
    "productName": "뤼튼 카피라이팅",
    "productPreview": "시간을 아껴주는 나만의 AI 카피라이터",
    "benefitPreview": "뤼튼 카피라이팅의 얼리 액세스 혜택 제공",
    "tag1": "🔮 마케팅툴",
    "tag2": "🤖 인공지능",
    "tag3": "🚲 생산성",
    "productDetail": "👉🏻 뤼튼 카피라이팅(wrtn Copywriting)은 초거대 모델을 활용하여 문장 생성을 도와주는 AI 카피라이터에요! 😀\n👉🏻 글쓰기가 발생하는 다양한 상황에서 Ideation을 돕고 좋은 결과물의 생성을 통해 여러분의 시간을 아껴드립니다.",
    "benefitDetail": "뤼튼 카피라이팅의 얼리 액세스 혜택을 제공해드립니다! 🥰",
    "isMakerlog": 0,
    "makerlogTitle": "",
    "makerlogPreviewtext": "",
    "makerlogLink": "",
    "profileImg": "https://assets.disquiet.io/images/profile/30a5d24d215e0c28612efed47e8c2fcc838f02aa7fd4a8ed9f44db47b35ad40f",
    "profileName": "유영준",
    "profileRole": "Head of Business@뤼튼테크놀로지스",
    "profileLink": "https://disquiet.io/@derek",
    "productLink": "https://disquiet.io/product/뤼튼-카피라이팅/",
    "tallyLink": "https://tally.so/r/3yPG5B",
    "popularity": ""
  },
  {
    "productId": 9,
    "productName": "싱크트리",
    "productPreview": "백엔드 노코드 개발 솔루션",
    "benefitPreview": "할인 및 무료 사용",
    "tag1": "🧑‍💻 개발툴",
    "tag2": "💻 노코드",
    "tag3": "🚲 생산성",
    "productDetail": "싱크트리는 개발 외 업무로 힘들어하는 개발자와 기업을 위해 탄생했습니다. 지금도 수많은 백엔드 개발자들이 프로젝트 때마다 새로운 환경 설정과 반복적인 배포 과정 때문에 개발을 시작하기도 전에 힘들어 하고 있습니다.\n\n게다가, 자금력이 부족한 초기 스타트업의 경우, 인프라, 서버 등 환경 설정 비용 부담으로 인해 프로젝트가 무산되는 경우도 있죠.\n\n쉬운 사용 방법, 즉각적인 생산성, 무료 사용으로도 누구나 개발 가능한 접근성까지 이제 싱크트리와 함께 개발 본연의 업무와 비즈니스 확장에 집중하세요!",
    "benefitDetail": "할인, 무료 사용",
    "isMakerlog": 1,
    "makerlogTitle": "싱크트리 기술 블로그 오픈!",
    "makerlogPreviewtext": "싱크트리 기술 블로그에서는 '엔터플 개발 문화', '싱크트리를 활용한 개발 사례', '싱크트리 관련 기술 이야기' 등의 소식을 만나보실 수 있습니다.",
    "makerlogLink": "https://disquiet.io/@grace_ntuple/makerlog/1734",
    "profileImg": "https://assets.disquiet.io/images/profile/2432e061e55aa05424415bfe17bf4b64188a779dd2a56201ba4967231c86f78c",
    "profileName": "Grace Nam",
    "profileRole": "마케팅 @엔터플",
    "profileLink": "https://disquiet.io/@grace_ntuple",
    "productLink": "https://disquiet.io/product/%EC%8B%B1%ED%81%AC%ED%8A%B8%EB%A6%AC",
    "tallyLink": "https://tally.so/r/3yPG5B",
    "popularity": ""
  },
  {
    "productId": 10,
    "productName": "데이터너겟",
    "productPreview": "봐야 할 리포트만 전달하고, 지금 필요한 솔루션을 추천해요.",
    "benefitPreview": "트랜잭션 툴 1회 무상 유지보수, 혹은 무료 기본설치",
    "tag1": "🔮 마케팅툴",
    "tag2": "📊 분석툴",
    "tag3": "🤖 인공지능",
    "productDetail": "GA4, Facebook Ads 등 수많은 리포트 중 봐야할 데이터만 큐레이팅하여 시각화 된 리포트로 볼 수 있는 서비스입니다.\n\n그로스해킹의 가설/ 실험/ 검증에 충실하기 위한 서비스들을 고민하고 개선해나가고 있습니다.",
    "benefitDetail": "현재 사용하고 있는 트랜잭션 툴(GA4, appsflyer, firebase 등)의 1회 무상 유지보수, 혹은 무료 기본설치 (이벤트 5개 추적)",
    "isMakerlog": 1,
    "makerlogTitle": "그로스해킹 솔루션, 그로스해킹 하기.",
    "makerlogPreviewtext": "제가 보려는게 그렇게 대단한 건 아니잖아요...\n\n저희는 LABBIT이라는 브랜드로 그로스해킹 서비스를 제공했습니다. 고객사의 KPI를 함께 고민하며 천여개의 고객사를 만나보니, 주된 니즈가...",
    "makerlogLink": "https://disquiet.io/@jaewoo/makerlog/1736",
    "profileImg": "https://assets.disquiet.io/images/profile/eb610fbca90b7b23dd96c063b1989a2fe74cb43e8e608071f3f71e7bbb53ff47",
    "profileName": "최재우",
    "profileRole": "대표이사 @(주) 위어드섹터",
    "profileLink": "https://disquiet.io/@jaewoo",
    "productLink": "https://disquiet.io/product/%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%84%88%EA%B2%9F",
    "tallyLink": "https://tally.so/r/3yPG5B",
    "popularity": ""
  },
  {
    "productId": 11,
    "productName": "스티비",
    "productPreview": "이메일 뉴스레터 서비스",
    "benefitPreview": "30% 할인 쿠폰을 제공",
    "tag1": "🔮 마케팅툴",
    "tag2": "💻 노코드",
    "tag3": "🎙 미디어",
    "productDetail": "스티비는 뉴스레터의 제작과 발송, 마케팅을 돕는 이메일 뉴스레터 서비스입니다. 누구나 쉽고 깔끔하게 뉴스레터를 발송하고, 구독자와의 특별한 관계를 경험할 수 있도록 스티비가 다양한 기능과 정보를 제공하고 있습니다.\n앞으로 어떤 방향으로 나아가야 할지 여러 고민을 하고 있고, 디스콰이엇에 계신 분들과도 이야기를 나눠보고 싶습니다. 🙂",
    "benefitDetail": "디스콰이엇 사용자 중, 스티비를 사용해보고 싶으시다면 30% 할인 쿠폰을 제공해드릴 수 있습니다. 제공 방법은 스티비 제휴 할인 신청 폼에 미리 지정한 할인 코드를 입력하여 확인하는 방식으로 진행됩니다.",
    "isMakerlog": 0,
    "makerlogTitle": "",
    "makerlogPreviewtext": "",
    "makerlogLink": "",
    "profileImg": "https://assets.disquiet.io/images/profile/6c6caae673b3f07dd2122d7520566a49d7d2f5a7ca42bdabd97a17f55f2bfba2",
    "profileName": "스티비",
    "profileRole": "이메일 뉴스레터 서비스@스티비",
    "profileLink": "https://disquiet.io/@stibee",
    "productLink": "https://disquiet.io/product/%EC%8A%A4%ED%8B%B0%EB%B9%84",
    "tallyLink": "https://tally.so/r/3yPG5B",
    "popularity": ""
  },
  {
    "productId": 12,
    "productName": "슈퍼코더",
    "productPreview": "해외개발자 채용 플랫폼",
    "benefitPreview": "할인 혜택(1회 매칭 fee 20% → 15%, 매월 관리 fee 10% → 7%)",
    "tag1": "🧑‍💻 개발툴",
    "tag2": "🏘 커뮤니티",
    "tag3": "📡 중개 플랫폼",
    "productDetail": "세컨드팀 (supercoder.co)은 개발자 채용에 어려움을 겪고 있는 기업들에게 개발자 역량 검증 및 국내&해외 개발자 채용 서비스를 제공하고 있는 Tech HR 스타트업입니다. 이로써 보다 글로벌하고 효과적인 개발 조직을 구축하실 수 있도록 도와드리고 있습니다. 현재 국내 tech 기업들의 고질적인 개발자 채용 문제를 우리만의 창의적인 방법으로 해결해 오고 있으며, 현재 top-tier 테크 기업에서 경험을 쌓은 co-founder 3명이 ‘개발자 역량 검증’, ‘단기 채용’, ‘장기 채용’ 세가지 서비스를 개발/운영 중입니다.",
    "benefitDetail": "할인 혜택을 제공하려 합니다.\n기존에 저희가 고객사들에게 받는 수수료가 두 가지 종류가 있습니다.\n1) One-time matching fee (최초 1회성)\n2) Monthly management fee (매달 발생하는 비용)\n\n1)의 경우 기존에는 저희를 통해 채용되는 개발자 분의 연봉의 20%,\n2)의 경우 기존에는 개발자 분의 월급의 10%를 청구하게 되는데요.\n\n디스콰이엇을 통해서 저희에게 연락 주시는 분들은 1)을 15%로 2)을 7%로 할인 드릴 예정입니다.",
    "isMakerlog": 1,
    "makerlogTitle": "시드 투자 유치 경험",
    "makerlogPreviewtext": "슈퍼코더 서비스를 만들고 있는 세컨드팀의 시드투자 유치 이야기를 적어보려고 합니다.\n\n우선 저희 회사의 간략한 background 정보를 알려드리자면 세컨드팀은 창업한지 6개월 된 극초기 스타트업이고 슈퍼코더 서비스를 운영한지는 3개월 정도가 되어갑니다.\n\n결론부터 말씀드리자면...",
    "makerlogLink": "https://disquiet.io/@kyle/makerlog/46",
    "profileImg": "https://assets.disquiet.io/images/profile/eb3e012338c2935543545714bcae46a56b8d0a4af007b35fa006c11da5f9ec11",
    "profileName": "정태헌",
    "profileRole": "CSO @Supercoder",
    "profileLink": "https://disquiet.io/@tjeong",
    "productLink": "https://disquiet.io/product/%EC%8A%88%ED%8D%BC%EC%BD%94%EB%8D%94",
    "tallyLink": "https://tally.so/r/3yPG5B",
    "popularity": ""
  },
  {
    "productId": 13,
    "productName": "되는시간",
    "productPreview": "되는시간 - 내가 되는 시간을 상대방이 예약할 수 있어요.",
    "benefitPreview": "무료 1개월 사용권",
    "tag1": "💸 세일즈",
    "tag2": "💻 노코드",
    "tag3": "🚲 생산성",
    "productDetail": "내가 되는 시간을 상대방이 예약할 수 있어요.\n\n팀소개\n- 저희는 초중고 동창으로 이루어진 팀입니다.\n- 오랫동안 연락 안하고 지내다가 우연히 스타트업에서 만났습니다!",
    "benefitDetail": "무료 1개월 사용권",
    "isMakerlog": 1,
    "makerlogTitle": "SaaS 랜딩 페이지 전환율 공부",
    "makerlogPreviewtext": "되는시간 (https://whattime.co.kr) 서비스를 만들고 있는 김재영입니다.\n\n주기적으로 서비스 퍼널을 분석 하며 서비스를 개선해 나가고 있는데요, 부족하지만 해당 내용 공유해 드립니다.\n\n많은 서비스가 그렇듯 왜 가입자 수가 확 늘지 않을까 하는 고민을...",
    "makerlogLink": "https://disquiet.io/@whattime-jay/makerlog/1008",
    "profileImg": "https://assets.disquiet.io/images/profile/be7ace368088c5f2e787da46878215b1e81421664e8539e1d31d12668f487702",
    "profileName": "Hanna Oh",
    "profileRole": "되는시간 Co-founder&COO @왓타임",
    "profileLink": "https://disquiet.io/@jane6966",
    "productLink": "https://disquiet.io/product/%EB%90%98%EB%8A%94%EC%8B%9C%EA%B0%84-1644990364167",
    "tallyLink": "https://tally.so/r/3yPG5B",
    "popularity": ""
  },
  {
    "productId": 14,
    "productName": "셀렉트 Select",
    "productPreview": "스타트업을 위한 어드민, 백오피스 솔루션",
    "benefitPreview": "크레딧 제공 & 관리자 페이지 5개 제작 지원",
    "tag1": "🧑‍💻 개발툴",
    "tag2": "💻 노코드",
    "tag3": "🚲 생산성",
    "productDetail": "개발팀 입장에서는 제품 개선하기도 바쁜데 어드민까지 만들어야하고\n운영팀은 백오피스 기능에 대한 니즈가 높지만 포기할 수 밖에 없는 아쉬운 상황이었는데요.\n\n기존의 어드민 개발 방식보다 더 나은 방법이 필요하다고 생각했습니다.\n\n이를 해결하고자 '셀렉트'는 어드민을 10배 더 쉽게 만들 수 있는 솔루션을 제공합니다.\n☑️ 기존에 사용하던 SQL 쿼리, HTTP API 호출정보가 어드민이 됩니다.\n☑️ 별도의 UI, 백엔드 개발이 필요하지 않습니다.\n☑️ 어드민에서 자주 사용하는 기능을 빌트인으로 제공합니다.\n(구글 로그인, 구글 시트로 내보내기 등)",
    "benefitDetail": "- 60만원 상당의 크레딧 제공\n- 관리자 페이지 5개 제작 지원",
    "isMakerlog": 0,
    "makerlogTitle": "",
    "makerlogPreviewtext": "",
    "makerlogLink": "",
    "profileImg": "https://assets.disquiet.io/images/profile/5c13a3b756d05154579dec9df13202305afeefb3adad3a4c7c6091a870be3fd0",
    "profileName": "김학범",
    "profileRole": "제품 매니저 @셀렉트",
    "profileLink": "https://disquiet.io/@hkim",
    "productLink": "https://disquiet.io/product/%EC%85%80%EB%A0%89%ED%8A%B8-select",
    "tallyLink": "https://tally.so/r/3yPG5B",
    "popularity": ""
  },
  {
    "productId": 15,
    "productName": "스타우터",
    "productPreview": "IT 스타터를 위한 모든 것!",
    "benefitPreview": "IT 서비스 제작 가이드 및 템플릿 무료 제공",
    "tag1": "🎨 디자인",
    "tag2": "🚲 생산성",
    "tag3": "✏️ 교육",
    "productDetail": "4년간 IT 서비스의 기획&디자인&개발 모든 과정을 함께한 에이전시 Tirrilee가\n초기 서비스 제작자 분들을 위해 새로운 서비스를 시작합니다 🥳\n\n🌈 스타우터 MVP 테스트 진행중! 아래의 결과 자료를 무료로 받아보세요!\n1️⃣ 기능 요구사항 정의서\n2️⃣ 기능 구조도\n3️⃣ 기능 별 예시화면\n4️⃣ 초기 기획 가이드\n5️⃣ 초기 기획서 양식",
    "benefitDetail": "- IT 서비스 제작 가이드 및 템플릿 무료 제공\n- 기능 요구사항 정의서 작성\n- 기능 구조도\n- 기능 별 예시화면 제공",
    "isMakerlog": 0,
    "makerlogTitle": "",
    "makerlogPreviewtext": "",
    "makerlogLink": "",
    "profileImg": "https://assets.disquiet.io/images/profile/fbd0ffd8faa00dee6b3144129da279db3bde4e17b2a865f7171e48b32abc1881",
    "profileName": "스타우터",
    "profileRole": "PO ・ UXUI Design ・Developer @스타우터",
    "profileLink": "https://disquiet.io/@stauter",
    "productLink": "https://disquiet.io/product/스타우터/",
    "tallyLink": "https://tally.so/r/3yPG5B",
    "popularity": ""
  },
  {
    "productId": 16,
    "productName": "Outcode",
    "productPreview": "문서작성처럼 쉽고 빠르게 업무툴 만들기. Develop-on-Doc.",
    "benefitPreview": "할인 혜택 & 온라인/오프라인 온보딩 제공",
    "tag1": "🧑‍💻 개발툴",
    "tag2": "💻 노코드",
    "tag3": "🚲 생산성",
    "productDetail": "우리 팀 업무에 딱 맞는 업무툴은 어디 없을까요? 원하는 대로 바로바로, 쉽게 업무툴을 만들어 쓸 수 있다면 얼마나 좋을까요?\n\n문서를 작성하듯이 쉽게, 가장 친숙한 방법으로 시작하세요. 나머지는 아웃코드가 책임집니다!",
    "benefitDetail": "디스콰이엇을 통해 신청해주신 분들께는 할인 혜택과 온라인/오프라인 온보딩을 제공할 예정입니다.",
    "isMakerlog": 1,
    "makerlogTitle": "아웃코드를 시작한 이유",
    "makerlogPreviewtext": "아웃코드팀은 일반 사용자를 위한 가장 심플하고 새로운 데이터 자동화 플랫폼을 만들고 있습니다. 우리의 미션은 전문지식이 없이도, 개발자가 아니어도 데이터를 쉽게 사용할 수 있도록 하는 것입니다. 우리가 개발하는 플랫폼인 아웃코드는 회사에서 쌓여가는 데이터를 누구나 쉽게 사용하기 위해 코드, 쿼리, 스크립트, 심지어 워크플로우까지 필요없는 새로운 형태의 가장 쉬운 경험을 제공하려고...",
    "makerlogLink": "https://disquiet.io/@outcode/makerlog/1922",
    "profileImg": "https://assets.disquiet.io/images/profile/fdbe47ee97fbd45afb32e2b15438f39ef73acafc5d8942941bead250337a0ad8",
    "profileName": "Lea Lim",
    "profileRole": "마케팅@아웃코드",
    "profileLink": "https://disquiet.io/@lea_at_outcode",
    "productLink": "https://disquiet.io/product/outcode",
    "tallyLink": "https://tally.so/r/3yPG5B",
    "popularity": ""
  },
  {
    "productId": 17,
    "productName": "클랩CLAP",
    "productPreview": "팀 피드백 문화를 도와주는 솔루션",
    "benefitPreview": "20개 기업 한정으로 조직 문화 진단을 제공",
    "tag1": "🚲 생산성",
    "tag2": "🎙 미디어",
    "tag3": "",
    "productDetail": "팀 성장을 위한 피드백 문화의 시작 CLAP\nCLAP을 통해 팀과 팀원의 성장을 돕고 지속적인 피드백을 할 수 있는 환경을 만들어보세요!\n\n👏🏻CLAP 어떤 서비스를 제공하나요?\n클랩은 조직과 구성원의 성장 및 이를 위한 피드백 문화 정착을 지원하는 다양한 기능이 준비되어 있습니다.",
    "benefitDetail": "메이커 키트 신청 혜택:20개 기업 한정으로 조직 문화 진단을 제공합니다.\n\n조직 문화 진단 효과:현재 회사에 존재하는 제도와 문화 중 구성원들의 생각과 차이를 파악할 수 있고 효과가 미비한 부분을 사전에 확인 후 개선시킬 수 있습니다.\n\n혜택 신청 순서\n1)메이커키트를 통해 클랩 유료 결제 시 '채널톡'을 통해 문의주세요!\n2)확인 후 2주 내 담당 매니저가 메일로 조직 문화 진단 템플릿을 제공드립니다. \n3)템플릿에 맞게 내용을 제출해 주세요.\n4)조직 문화 진단 결과를 메일로 공유드립니다.",
    "isMakerlog": 0,
    "makerlogTitle": "",
    "makerlogPreviewtext": "",
    "makerlogLink": "",
    "profileImg": "https://assets.disquiet.io/images/profile/32d788754ccafcf0792d37bc46191820bf4846fb9ebec9c6efe6f05d88c199d7",
    "profileName": "한혜민",
    "profileRole": "마케팅@디웨일",
    "profileLink": "https://disquiet.io/@dwhale_hyem",
    "productLink": "https://disquiet.io/product/clap",
    "tallyLink": "https://tally.so/r/3yPG5B",
    "popularity": ""
  },
  {
    "productId": 18,
    "productName": "슬리드",
    "productPreview": "동영상 학습에 최적화된 필기 노트",
    "benefitPreview": "프리미엄 회원권 1년권 & 크리에이터 지원 가능",
    "tag1": "🚲 생산성",
    "tag2": "✏️ 교육",
    "tag3": "",
    "productDetail": "영상 속 지식을 내 것으로, 슬리드'\n\n슬리드는 유튜브, 온라인 클래스, 줌 등 동영상을 보는 동시에 쉽게 화면을 캡쳐하며 필기를 남길 수 있는 영상에 최적화된 노트 툴입니다.",
    "benefitDetail": "- 슬리드 프리미엄 회원권 1년권 (13만원 상당)\n- 슬리드 크리에이터 지원 가능\n- (슬리드 크리에이터 지원시) 슬리드 대표와의 1대1 온보딩 및 AMA 세션",
    "isMakerlog": 0,
    "makerlogTitle": "",
    "makerlogPreviewtext": "",
    "makerlogLink": "",
    "profileImg": "https://assets.disquiet.io/images/profile/d4435e14e0ddeadcf4e771d301cb9cf714481647ce920d1dc03e821a765a1f8d",
    "profileName": "Junghyun Park",
    "profileRole": "CEO @슬리드",
    "profileLink": "https://disquiet.io/@junghyun",
    "productLink": "https://disquiet.io/product/슬리드/",
    "tallyLink": "https://tally.so/r/3yPG5B",
    "popularity": ""
  }
];